<a href="https://colab.research.google.com/github/adilsaid64/Data-Analysis-and-Machine-Learning-Courses/blob/main/data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd #used to precess data sets and import them

## Importing the dataset

In any data set where you are going to train a machine learning model, you have features, and depedenat variables.

features are -independant variables.dependant variable - in this case, if the customer purchacesd. usally the last column in data set. 

In [ ]:
dataset = pd.read_csv("Data.csv") #data frame

#create matrix of features and dependent variable vector.

#all the rows, and all the columns except the last one. rows --, column |
X = dataset.iloc[:, :-1].values

#takes the last column
y = dataset.iloc[:,-1].values


In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

*   Removing data, sometimes in large data sets you can just delete the entire entry that contains the missing data. Removing a few entires from a large data wont affect it much. this is one moethod.

*   Replacing missing values by average of all varialbes in column. Classic way of handling missing data.




In [ ]:
from sklearn.impute import SimpleImputer #class
imputer = SimpleImputer(missing_values=np.nan, strategy="mean") #this is an object of the class
imputer.fit(X[:, 1:3])
imputer.transform(X[:, 1:3])

X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data (Dummy Variables)

### Encoding the Independent Variable

*   Encoding them as 0,1,2 can have potential and missinterpretation by the model. It might start odering the indepentant catorical varialbes.
*   One hut encoding. Turning into 3 columns, since we have 3 differnt catogories. Binary Vectors for each of the county

*   This way we use vectors for example <France, Spain, German>, So if we want France we do <1,0,0> etc




In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

We can use Binary for the Yes and no.so 1,0.

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

We will get 4 sets.
2 from the training data and 2 from the testing data.
matrix of features and dependant variables sets from both datasets. This is the format expected by the model.


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state  =1)#random state sets the seed to not get different results.

In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

Scaling all features to make sure they take values in the same scale to prevent one feature from dominating the other.
This occurs after. Test set is supposed to be considered a brand new set, to evaluate the model. So this is the reason we dont work on the test set. We treat it as new data. Doing Feature Scaling first, results in information leakage.

Types of feature scaling.

 

*   Normalisation - when you have a normal distribution in most of features.(Specific sitiation)
 
*   Standardisation - works well all the time. Values are between -3 and +3


*   Dont apply to Catogorical Dummy Varialbes.



In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

#from column 3 and onwards to avoid scaling catogorical data
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])




In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
